package ir.reyminsoft;

public class PersianLeapYears {
    /*
     * This array contains 3000 boolean values with 726 of them set to 'true' representing leap years.
     * usage: persianLeapYears[year]
     *
     * Persian leap years do not follow a simple rule, and there is no linear pattern to calculate them.
     * all the formulas found online are wrong in one way or another. they are computational approximations and often
     * do not match the official leap years calculated by the department of geophysics at the university of tehran.
     *
     * the leap years are stored as a boolean array for 2 purposes:
     *  1. the process of determining if a given year is a leap year or not completes instantly.
     *     (array lookup is faster than formulas or a hashset lookup)
     *  2. this boolean array takes less memory space than arrays of other types.
     *
     *
     * */
    public static final boolean[] persianLeapYears = new boolean[]{
            false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true,
            false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false,
            true, false, false, false, true, false, false, false
    };

}
